[project]
name = 'Blockchain-Based-Insurance-Claims-Processing'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.policy-verification]
path = 'contracts/policy-verification.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
